In [3]:
import pandas as pd
import csv

In [5]:
tsv_data = pd.read_csv('Resources/state_market_tracker.tsv000', sep='\t')
tsv_data['property_type']

0        Single Family Residential
1                        Townhouse
2                      Condo/Co-op
3                        Townhouse
4        Single Family Residential
                   ...
27301                    Townhouse
27302    Single Family Residential
27303    Single Family Residential
27304      Multi-Family (2-4 Unit)
27305                    Townhouse
Name: property_type, Length: 27306, dtype: object

In [6]:
tsv_data['period_end'].value_counts()
tsv_data.columns

Index(['period_begin', 'period_end', 'period_duration', 'region_type',
       'region_type_id', 'table_id', 'is_seasonally_adjusted', 'region',
       'city', 'state', 'state_code', 'property_type', 'property_type_id',
       'median_sale_price', 'median_sale_price_mom', 'median_sale_price_yoy',
       'median_list_price', 'median_list_price_mom', 'median_list_price_yoy',
       'median_ppsf', 'median_ppsf_mom', 'median_ppsf_yoy', 'median_list_ppsf',
       'median_list_ppsf_mom', 'median_list_ppsf_yoy', 'homes_sold',
       'homes_sold_mom', 'homes_sold_yoy', 'pending_sales',
       'pending_sales_mom', 'pending_sales_yoy', 'new_listings',
       'new_listings_mom', 'new_listings_yoy', 'inventory', 'inventory_mom',
       'inventory_yoy', 'months_of_supply', 'months_of_supply_mom',
       'months_of_supply_yoy', 'median_dom', 'median_dom_mom',
       'median_dom_yoy', 'avg_sale_to_list', 'avg_sale_to_list_mom',
       'avg_sale_to_list_yoy', 'sold_above_list', 'sold_above_list_mom',
       'sold_above_list_yoy', 'price_drops', 'price_drops_mom',
       'price_drops_yoy', 'off_market_in_two_weeks',
       'off_market_in_two_weeks_mom', 'off_market_in_two_weeks_yoy',
       'parent_metro_region', 'parent_metro_region_metro_code',
       'last_updated'],
      dtype='object')

In [9]:
tsv_df=tsv_data[['period_end', 'state', 'state_code', 'property_type', 'median_sale_price', 'median_list_price', 'median_ppsf', 'homes_sold', 'pending_sales', 'inventory', 'median_dom', 'avg_sale_to_list', 'sold_above_list', 'price_drops', 'off_market_in_two_weeks', 'parent_metro_region']].copy()
tsv_df.head()

,period_end,state,state_code,property_type,median_sale_price,median_list_price,median_ppsf,homes_sold,pending_sales,inventory,median_dom,avg_sale_to_list,sold_above_list,price_drops,off_market_in_two_weeks,parent_metro_region
0,2019-03-31,Missouri,MO,Single Family Residential,185000,196900.0,116.0,4009,348.0,8373.0,49.0,0.976008,0.222901,0.187746,0.481241,Midwest Region
1,2015-03-31,Arizona,AZ,Townhouse,154100,231600.0,116.0,762,655.0,2555.0,60.0,0.964465,0.076115,0.250489,0.235440,West Region
2,2013-12-31,Arkansas,AR,Condo/Co-op,113400,142100.0,95.0,14,7.0,194.0,65.0,0.958697,0.071429,NaN,0.076923,South Region
3,2017-11-30,Vermont,VT,Townhouse,227400,262300.0,154.0,57,31.0,259.0,84.0,0.971831,0.140351,0.108108,0.219708,Northeast Region
4,2012-11-30,Louisiana,LA,Single Family Residential,164700,169800.0,91.0,1390,437.0,6328.0,146.0,0.950232,0.119424,NaN,0.068764,South Region

In [17]:
#new_tsv_df=tsv_df['period_end'].str.split('-',expand=True)
tsv_df[['Year','Month','Day']] = tsv_df['period_end'].str.split('-', expand=True)

In [22]:
new_columns=['period_end','Year','Month', 'state', 'state_code', 'property_type',
       'median_sale_price', 'median_list_price', 'median_ppsf', 'homes_sold',
       'pending_sales', 'inventory', 'median_dom', 'avg_sale_to_list',
       'sold_above_list', 'price_drops', 'off_market_in_two_weeks',
       'parent_metro_region']

In [25]:
new_tsv_df=tsv_df[['period_end','Year','Month', 'state', 'state_code', 'property_type',
       'median_sale_price', 'median_list_price', 'median_ppsf', 'homes_sold',
       'pending_sales', 'inventory', 'median_dom', 'avg_sale_to_list',
       'sold_above_list', 'price_drops', 'off_market_in_two_weeks',
       'parent_metro_region']]

In [27]:
new_tsv_df['state'].value_counts()

Missouri          605
Nevada            605
Massachusetts     605
Arizona           605
Kentucky          605
Virginia          605
Ohio              605
Florida           605
Oregon            605
Pennsylvania      605
Washington        605
Columbia          605
Illinois          605
Colorado          605
Oklahoma          605
Minnesota         605
California        605
New York          605
South Carolina    605
New Hampshire     605
Georgia           605
Vermont           605
North Carolina    605
Utah              605
Idaho             605
Texas             605
New Jersey        605
Maryland          605
Nebraska          605
Wisconsin         604
Louisiana         604
Delaware          603
Mississippi       603
Kansas            603
Tennessee         590
Arkansas          589
Hawaii            575
New Mexico        547
Alabama           539
Connecticut       528
Michigan          506
Maine             504
Iowa              502
Rhode Island      493
Indiana           486
Alaska            484
West Virginia     401
Name: state, dtype: int64

In [32]:
zillow_df=pd.read_csv('Resources/State_zhvi_uc_sfrcondo_tier_0.33_0.67_sm_sa_month.csv')
house_value_df=zillow_df[['RegionName','StateName','2021-01-31', '2021-02-28', '2021-03-31','2021-04-30','2021-05-31','2021-06-30','2021-07-31','2021-08-31','2021-09-30','2021-10-31','2021-11-30','2021-12-31']]
new_house_value=house_value_df.rename(columns={'RegionName':'State','StateName':'StateCode','2021-01-31':'Jan-21','2021-02-28':'Feb-21','2021-03-31':'Mar-21','2021-04-30':'Apr-21','2021-05-31':'May-21','2021-06-30':'Jun-21','2021-07-31':'Jul-21','2021-08-31':'Aug-21','2021-09-30':'Sep-21','2021-10-31':'Oct-21','2021-11-30':'Nov-21','2021-12-31':'Dec-21'})

In [33]:
new_house_value

,State,StateCode,Jan-21,Feb-21,Mar-21,Apr-21,May-21,Jun-21,Jul-21,Aug-21,Sep-21,Oct-21,Nov-21,Dec-21
0,California,CA,618294.0,625422.0,633308.0,643641.0,658022.0,675339.0,694030.0,707798.0,717667.0,722682.0,728176.0,734984.0
1,Texas,TX,230876.0,233637.0,236573.0,240201.0,244509.0,249913.0,255534.0,261171.0,265994.0,270240.0,273854.0,278091.0
2,New York,NY,332201.0,335482.0,338694.0,341880.0,345926.0,350823.0,356409.0,361203.0,365205.0,368235.0,371094.0,373923.0
3,Florida,FL,272450.0,275593.0,279308.0,283324.0,288769.0,295636.0,303601.0,311672.0,319591.0,326995.0,334328.0,341156.0
4,Illinois,IL,218603.0,220648.0,222534.0,225041.0,227347.0,230491.0,233936.0,237319.0,239842.0,242067.0,244316.0,246807.0
5,Pennsylvania,PA,219213.0,221659.0,224161.0,226839.0,230402.0,234254.0,237710.0,240485.0,242640.0,244622.0,246484.0,248715.0
6,Ohio,OH,169582.0,171645.0,174099.0,176423.0,178931.0,181535.0,184120.0,186416.0,188455.0,190159.0,191858.0,193924.0
7,Michigan,MI,191790.0,194264.0,196749.0,199098.0,201901.0,205309.0,208868.0,212003.0,214298.0,216496.0,218099.0,220191.0
8,Georgia,GA,228357.0,231539.0,234887.0,238575.0,242811.0,247922.0,253406.0,258956.0,264244.0,269659.0,275091.0,281342.0
9,North Carolina,NC,230321.0,233771.0,237443.0,240914.0,245044.0,250052.0,255846.0,261953.0,267716.0,272901.0,277579.0,282791.0
10,New Jersey,NJ,375425.0,379860.0,384130.0,389233.0,395119.0,402214.0,409627.0,416394.0,421523.0,425516.0,428867.0,432060.0
11,Virginia,VA,310982.0,314330.0,318132.0,322057.0,326393.0,330736.0,334521.0,337721.0,340350.0,342789.0,345491.0,349193.0
12,Washington,WA,471124.0,477864.0,485535.0,494208.0,503700.0,516344.0,528126.0,539121.0,547056.0,554796.0,563536.0,572860.0
13,Massachusetts,MA,475371.0,481269.0,487218.0,493640.0,500938.0,510026.0,518996.0,526804.0,531778.0,536043.0,540072.0,544712.0
14,Indiana,IN,175163.0,177688.0,180307.0,182445.0,184854.0,187447.0,190314.0,193042.0,195541.0,197987.0,200449.0,203390.0
15,Arizona,AZ,313938.0,319799.0,327190.0,333379.0,343525.0,354112.0,365938.0,375668.0,383328.0,390537.0,396460.0,402109.0
16,Tennessee,TN,217066.0,220002.0,223033.0,225908.0,229424.0,233678.0,238535.0,243543.0,248448.0,253221.0,258102.0,263938.0
17,Missouri,MO,183507.0,185935.0,188672.0,191373.0,194136.0,196848.0,199576.0,201936.0,203948.0,205851.0,207846.0,210461.0
18,Maryland,MD,341510.0,345610.0,350164.0,355172.0,359376.0,363489.0,367467.0,371240.0,374173.0,376955.0,379575.0,382060.0
19,Wisconsin,WI,215851.0,218499.0,221273.0,223829.0,226603.0,229926.0,233248.0,236041.0,238124.0,239865.0,241484.0,243534.0
20,Minnesota,MN,280899.0,283735.0,286847.0,289069.0,292482.0,296527.0,301433.0,305068.0,307709.0,309547.0,311589.0,314468.0
21,Colorado,CO,443604.0,449631.0,456612.0,464332.0,474216.0,485791.0,497610.0,507267.0,514943.0,521715.0,528885.0,537071.0
22,Alabama,AL,161677.0,163621.0,165766.0,167506.0,169521.0,171857.0,174516.0,177116.0,179471.0,181644.0,183716.0,186850.0
23,South Carolina,SC,213079.0,215439.0,217958.0,220776.0,223845.0,227852.0,232167.0,237103.0,241963.0,246958.0,251687.0,256791.0
24,Louisiana,LA,181823.0,183134.0,184477.0,185638.0,186965.0,188734.0,190823.0,193096.0,195154.0,197127.0,198723.0,201069.0
25,Kentucky,KY,161210.0,162885.0,164792.0,166559.0,168432.0,170506.0,172694.0,174585.0,176377.0,178078.0,179803.0,182588.0
26,Oregon,OR,411371.0,416684.0,423103.0,430370.0,438676.0,448288.0,457959.0,465942.0,472101.0,476835.0,481493.0,486165.0
27,Oklahoma,OK,144197.0,145524.0,147022.0,148411.0,150220.0,152275.0,154324.0,156225.0,158030.0,159962.0,161978.0,164722.0
28,Connecticut,CT,288256.0,292584.0,297094.0,301796.0,307071.0,313044.0,318894.0,322910.0,325547.0,327401.0,329331.0,331409.0
29,Iowa,IA,160811.0,162564.0,164471.0,165968.0,167340.0,168949.0,170634.0,172125.0,173752.0,175178.0,176685.0,178752.0
30,Mississippi,MS,138359.0,139889.0,141386.0,142681.0,144021.0,145487.0,147169.0,148787.0,150364.0,151626.0,152926.0,155411.0
31,Arkansas,AR,142015.0,143601.0,145552.0,147126.0,149166.0,151113.0,153366.0,155341.0,157382.0,159096.0,160935.0,163730.0
32,Kansas,KS,170390.0,172721.0,175082.0,176963.0,178956.0,181221.0,183448.0,185584.0,187506.0,189480.0,190982.0,192936.0
33,Utah,UT,408582.0,416819.0,424527.0,434441.0,446565.0,461842.0,477073.0,489666.0,497806.0,505023.0,511475.0,520585.0
34,Nevada,NV,331039.0,335165.0,339498.0,344677.0,353554.0,364958.0,376728.0,385932.0,393760.0,400880.0,408096.0,414656.0
35,New Mexico,NM,228931.0,232304.0,235951.0,239011.0,242447.0,246425.0,250996.0,254711.0,258028.0,261045.0,264355.0,268221.0
36,West Virginia,WV,113452.0,114323.0,115326.0,116281.0,117085.0,117939.0,118848.0,119757.0,120620.0,121530.0,122418.0,124819.0
37,Nebraska,NE,196677.0,199382.0,202407.0,204738.0,207523.0,210266.0,212811.0,214663.0,216242.0,217662.0,219227.0,222215.0
38,Idaho,ID,351340.0,363598.0,376383.0,388023.0,398839.0,411409.0,423120.0,434620.0,441518.0,445607.0,447327.0,452432.0
39,Hawaii,HI,685410.0,692239.0,700777.0,709037.0,720563.0,733420.0,748845.0,763435.0,778614.0,792809.0,806300.0,816747.0
40,Maine,ME,276267.0,280393.0,285381.0,290407.0,297359.0,304829.0,312180.0,318215.0,321936.0,324607.0,326769.0,331323.0
41,New Hampshire,NH,333773.0,339301.0,344043.0,350307.0,356276.0,363825.0,370879.0,378052.0,383655.0,389033.0,393920.0,399636.0
42,Rhode Island,RI,339865.0,344481.0,349269.0,353929.0,360464.0,367637.0,376145.0,383533.0,389035.0,393509.0,396901.0,401522.0
43,Montana,MT,325423.0,332317.0,339216.0,345968.0,353491.0,362049.0,370946.0,380548.0,389223.0,396735.0,402631.0,410643.0
44,Delaware,DE,283679.0,286176.0,288945.0,292618.0,297363.0,302536.0,307451.0,312639.0,317736.0,322134.0,326057.0,329226.0
45,South Dakota,SD,230143.0,233777.0,238086.0,241547.0,244893.0,248455.0,251852.0,255089.0,258028.0,260669.0,263287.0,267669.0
46,Alaska,AK,301441.0,301855.0,301434.0,302204.0,303721.0,304931.0,305777.0,307414.0,308693.0,309873.0,308763.0,309914.0
47,North Dakota,ND,238231.0,240001.0,241628.0,243114.0,244562.0,246319.0,248245.0,250053.0,251964.0,253681.0,255364.0,257578.0
48,Vermont,VT,279080.0,282622.0,286663.0,290018.0,294649.0,298419.0,302727.0,307146.0,312729.0,317509.0,321283.0,326047.0
49,District of Columbia,DC,659158.0,660648.0,666107.0,670317.0,677271.0,682042.0,685609.0,686057.0,686186.0,688436.0,688957.0,689844.0
50,Wyoming,WY,267953.0,270181.0,272745.0,274741.0,276782.0,279279.0,281810.0,284588.0,287222.0,289772.0,292168.0,297689.0